name: Testing setup
on:
  push:
    branches:
      - main
  
jobs:
  check-if-modified:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    outputs:
      modified: ${{ steps.check-latest.outputs.modified }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main
      - name: check-latest
        id: check-latest
        run: |
          current_commit=$(curl -sL https://api.github.com/repos/JobPetrovcic/agda-unimath/commits | jq -r '.[0].sha')
          if [[ "$current_commit" == "$(cat last_commit.txt)" ]]
          then 
            value=false 
          else
            value=true
          fi
          echo "$current_commit"
          ls
          cat last_commit.txt
          echo "Is modifier: $value"
          echo "modified=$value" >> $GITHUB_OUTPUT
          echo $current_commit > last_commit.txt
      - uses: stefanzweifel/git-auto-commit-action@v5

  job2:
    runs-on: ubuntu-latest
    needs: check-if-modified
    if: ${{ needs.check-if-modified.outputs.modified == 'true' }}
    steps:
      - run: echo "hello"
  #check:
  #  name: Visualize library
  #  runs-on: ubuntu-latest
  #  needs: check-if-modified
  #  if: ${{ needs.check-if-modified.outputs.modified == 'true' }}
  #  steps:
  #    - name: check-latest
  #      id: check-latest
  #      run: echo "hello"
  #    - uses: actions/checkout@v4
  #      with:
  #        repository: JobPetrovcic/agda-unimath
  #        ref: master
  #        path: mylib
  #    - uses: actions/checkout@v4
  #      with:
  #        repository: JobPetrovcic/agda-proof-assistent-assistent
  #        token: ${{ secrets.ACCESS }}
  #        ref: master
  #        path: agda-proof-assistent-assistent
  #    - uses: JobPetrovcic/Mathematical-Library-Vizualizer@main
  #      with:
  #        language: agda
  #        file_type: src/everything.lagda.md
  #        mode: standalone
  #        install_libs: no
  #        additional_commands: "make src/everything.lagda.md"
  #    - uses: cpina/github-action-push-to-another-repository@main
  #      env:
  #        API_TOKEN_GITHUB: ${{ secrets.ACCESS }}
  #      with:
  #        source-directory: "output"
  #        destination-github-username: "JobPetrovcic"
  #        destination-repository-name: "Visualize-Unimath"
  #        user-email: job1.petrovcic@gmail.com
  #        target-branch: main